/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PokerHandVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commitHand"
      | "commitments"
      | "getHandData"
      | "owner"
      | "renounceOwnership"
      | "revealHand"
      | "transferOwnership"
      | "verifyHand"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "HandCommitted"
      | "HandRevealed"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commitHand",
    values: [string, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHandData",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealHand",
    values: [string, BigNumberish, string, string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHand",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "commitHand", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHandData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealHand", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyHand", data: BytesLike): Result;
}

export namespace HandCommittedEvent {
  export type InputTuple = [
    tableId: string,
    handNumber: BigNumberish,
    commitmentHash: BytesLike,
    vrfRequestId: BigNumberish
  ];
  export type OutputTuple = [
    tableId: string,
    handNumber: bigint,
    commitmentHash: string,
    vrfRequestId: bigint
  ];
  export interface OutputObject {
    tableId: string;
    handNumber: bigint;
    commitmentHash: string;
    vrfRequestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HandRevealedEvent {
  export type InputTuple = [tableId: string, handNumber: BigNumberish];
  export type OutputTuple = [tableId: string, handNumber: bigint];
  export interface OutputObject {
    tableId: string;
    handNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PokerHandVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): PokerHandVerifier;
  waitForDeployment(): Promise<this>;

  interface: PokerHandVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commitHand: TypedContractMethod<
    [
      tableId: string,
      handNumber: BigNumberish,
      commitmentHash: BytesLike,
      vrfRequestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  commitments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        commitmentHash: string;
        vrfRequestId: bigint;
        commitTimestamp: bigint;
        committed: boolean;
      }
    ],
    "view"
  >;

  getHandData: TypedContractMethod<
    [tableId: string, handNumber: BigNumberish],
    [
      [string, string[], string, string, bigint, bigint, bigint] & {
        serverSeed: string;
        playerSeeds: string[];
        deckOrder: string;
        commitHash: string;
        vrfRequestId: bigint;
        commitTimestamp: bigint;
        revealTimestamp: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revealHand: TypedContractMethod<
    [
      tableId: string,
      handNumber: BigNumberish,
      serverSeed: string,
      playerSeeds: string[],
      deckOrder: string
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyHand: TypedContractMethod<
    [tableId: string, handNumber: BigNumberish],
    [
      [boolean, boolean, string, bigint] & {
        committed: boolean;
        revealed: boolean;
        commitHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commitHand"
  ): TypedContractMethod<
    [
      tableId: string,
      handNumber: BigNumberish,
      commitmentHash: BytesLike,
      vrfRequestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        commitmentHash: string;
        vrfRequestId: bigint;
        commitTimestamp: bigint;
        committed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHandData"
  ): TypedContractMethod<
    [tableId: string, handNumber: BigNumberish],
    [
      [string, string[], string, string, bigint, bigint, bigint] & {
        serverSeed: string;
        playerSeeds: string[];
        deckOrder: string;
        commitHash: string;
        vrfRequestId: bigint;
        commitTimestamp: bigint;
        revealTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealHand"
  ): TypedContractMethod<
    [
      tableId: string,
      handNumber: BigNumberish,
      serverSeed: string,
      playerSeeds: string[],
      deckOrder: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyHand"
  ): TypedContractMethod<
    [tableId: string, handNumber: BigNumberish],
    [
      [boolean, boolean, string, bigint] & {
        committed: boolean;
        revealed: boolean;
        commitHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "HandCommitted"
  ): TypedContractEvent<
    HandCommittedEvent.InputTuple,
    HandCommittedEvent.OutputTuple,
    HandCommittedEvent.OutputObject
  >;
  getEvent(
    key: "HandRevealed"
  ): TypedContractEvent<
    HandRevealedEvent.InputTuple,
    HandRevealedEvent.OutputTuple,
    HandRevealedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "HandCommitted(string,uint256,bytes32,uint256)": TypedContractEvent<
      HandCommittedEvent.InputTuple,
      HandCommittedEvent.OutputTuple,
      HandCommittedEvent.OutputObject
    >;
    HandCommitted: TypedContractEvent<
      HandCommittedEvent.InputTuple,
      HandCommittedEvent.OutputTuple,
      HandCommittedEvent.OutputObject
    >;

    "HandRevealed(string,uint256)": TypedContractEvent<
      HandRevealedEvent.InputTuple,
      HandRevealedEvent.OutputTuple,
      HandRevealedEvent.OutputObject
    >;
    HandRevealed: TypedContractEvent<
      HandRevealedEvent.InputTuple,
      HandRevealedEvent.OutputTuple,
      HandRevealedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
